---
title: "p8105_hw1_cj2493"
author: "Courtney Johnson"
date: 2018-9-13
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Problem 1

```{r, variable_definition}
set.seed(1)
problem_1_df = tibble(
  vec_numerical = runif(10, min = 0, max = 5),
  vec_logical = vec_numerical > 2,
  vec_char = c("Courtney", "Patrick", "Evelyn", "Glenn", "Sue", "Glen", "Jenny", "Kayla", "Lindsay", "Derick"),
  vec_fac = c("female", "male", "female", "male", "female", "male", "female", "female", "female", "male"),
  vec_factor = factor(vec_fac)
)

numerical_mean = mean(problem_1_df$vec_numerical)
logical_mean = mean(problem_1_df$vec_logical)
char_mean = mean(problem_1_df$vec_char)
factor_mean = mean(problem_1_df$vec_factor)
```

## What works and doesn't work when taking means?

The mean(x) function works for the numerical and logical vectors, but not for the character and factor vectors.

```{r, variable_conversion, include = FALSE}
convert_logical = as.numeric(problem_1_df$vec_logical)
convert_char = as.numeric(problem_1_df$vec_char)
convert_factor = as.numeric(problem_1_df$vec_factor)
```

## What happened?

The logical and factor vectors were converted to a numeric vector, but the character vector was not. 

```{r, convert_char}
char_to_factor = factor(problem_1_df$vec_char)
convert_char_2 = as.numeric(char_to_factor)
```

## Problem 2

```{r}

```

